set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
" Plugin 'Valloric/YouCompleteMe'

" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin)
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'terryma/vim-multiple-cursors'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

""" NERDTree 
"autocmd vimenter * NERDTree
map <C-n> :NERDTreeToggle<CR>

""" Vim
" [Tip] For OS X users: To copy paste with mouse=a use alt instead of Shift to
" selec the text. Then cmd-c and cmd-v work as expected.
set mouse=a

" turn off autoindent when you paste code
set paste

" set tab characters that appear 4-spaces-wide
set tabstop=4

" make backspace key work in insert mode
set backspace=indent,eol,start

" turn on search highlighting
set hlsearch


"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

nnoremap <C-P> :CtrlPMixed<cr>

" Might need to run 'sudo apt-get install vim-gui-common' first
vmap <C-x> "+yi

" Default mapping
let g:multi_cursor_next_key='<C-j>'
let g:multi_cursor_prev_key='<C-k>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'
