set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

""" let Vundle manage Vundle, required
" Please don't use PluginInstall to install 'YouCompleteMe'
Plugin 'Valloric/YouCompleteMe'

Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
""" end

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

""" NERDTree 
"autocmd vimenter * NERDTree
map <F2> :NERDTreeToggle<CR>

""""""""""""""""""""""""""""" Vim """""""""""""""""""""""""""""
" [Tip] For OS X users: To copy paste with mouse=a use alt instead of Shift to
" selec the text. Then cmd-c and cmd-v work as expected.
set mouse=a
" Turn off autoindent when you paste code
set paste
" Set tab characters that appear 4-spaces-wide
set tabstop=4   
" make backspace key work in insert mode
set backspace=indent,eol,start

""" Split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

""" Bind vim navigation keys to switching between tabs
" Moves to the next tab
map <C-l> :tabn<CR>
" Moves to the previous tab
map <C-h> :tabp<CR>
" Moves to the next tab
map <C-n> :tabnew<CR>

"""""""""""""""""""""""""""""" CtrlPMixed """""""""""""""""""""""""""""
nnoremap <C-P> :CtrlPMixed<cr>

" Might need to run 'sudo apt-get install vim-gui-common' first
vmap <C-c> "+yi
